# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: mealpoints
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: mealpoints-app-serverless
# "service" is the name of this project. This will also be added to your AWS resource names.
service: mealpoints-be-serverless

frameworkVersion: '3.38.0'

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies



package:
  patterns:
    - '!coverage/**'
    - '!test/**'
    - '!secrets.yml'
    - '!node_modules/**'

provider: 
  name: aws
  runtime: nodejs20.x
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  api:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
