export enum HttpMethodsEnum {
  Get = "GET",
  Post = "POST",
  Put = "PUT",
  Delete = "DELETE",
}

export enum OpenAIMessageTypesEnum {
  Text = "text",
  Image = "image",
  Audio = "audio",
  Video = "video",
  Document = "document",
  Sticker = "sticker",
}

export enum MessageTypesEnum {
  Audio = "audio", // for audio messages.
  Contacts = "contacts", // for contact messages.
  Document = "document", // for document messages.
  Image = "image", // for image messages.
  Interactive = "interactive", // for list and reply button messages.
  Location = "location", // for location messages.
  Reaction = "sticker", // for reaction messages.
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  Sticker = "sticker", // for sticker messages.
  Template = "template", // for template messages. Text and media (images and documents) message templates are supported.
  Text = "text", // for text messages.
  Video = "video", // for video messages
}

export enum UserEngagementMessageTypesEnum {
  Summary = "summary",
  Reminder = "reminder",
  MealReport = "meal_report",
  Welcome = "welcome",
}

export enum ParametersTypesEnum {
  Currency = "currency",
  DateTime = "date_time",
  Document = "document",
  Image = "image",
  Text = "text",
  Video = "video",
  Payload = "payload",
}

export enum InteractiveTypesEnum {
  Button = "button",
  List = "list",
  Product = "product",
  ProductList = "product_list",
}

export enum ButtonTypesEnum {
  QuickReply = "quick_reply",
  URL = "url",
}

export enum ButtonPositionEnum {
  First,
  Second,
  Third,
}

export enum ComponentTypesEnum {
  Header = "header",
  Body = "body",
  Button = "button",
}

export enum WAConfigEnum {
  BaseURL = "WA_BASE_URL",
  AppId = "M4D_APP_ID",
  AppSecret = "M4D_APP_SECRET",
  PhoneNumberId = "WA_PHONE_NUMBER_ID",
  BusinessAcctId = "WA_BUSINESS_ACCOUNT_ID",
  APIVersion = "CLOUD_API_VERSION",
  AccessToken = "CLOUD_API_ACCESS_TOKEN",
  WebhookEndpoint = "WEBHOOK_ENDPOINT",
  WebhookVerificationToken = "WEBHOOK_VERIFICATION_TOKEN",
  ListenerPort = "LISTENER_PORT",
  MaxRetriesAfterWait = "max_runs_on_a_thread_AFTER_WAIT",
  RequestTimeout = "REQUEST_TIMEOUT",
  Debug = "DEBUG",
}

export enum WARequiredConfigEnum {
  APIVersion = "CLOUD_API_VERSION",
  AccessToken = "CLOUD_API_ACCESS_TOKEN",
}

export enum ConversationTypesEnum {
  BusinessInitiated = "business_initiated",
  CustomerInitiated = "customer_initiated",
  ReferralConversion = "referral_conversion",
}

export enum StatusEnum {
  Delivered = "delivered",
  Read = "read",
  Sent = "sent",
  Failed = "failed", // Custom status added to handle failed messages. Not sent by WhatsApp
}

export enum VideoMediaTypesEnum {
  Mp4 = "video/mp4",
  Threegp = "video/3gp",
}

export enum StickerMediaTypesEnum {
  Webp = "image/webp",
}

export enum ImageMediaTypesEnum {
  Jpeg = "image/jpeg",
  Png = "image/png",
}

export enum DocumentMediaTypesEnum {
  Text = "text/plain",
  Pdf = "application/pdf",
  Ppt = "application/vnd.ms-powerpoint",
  Word = "application/msword",
  Excel = "application/vnd.ms-excel",
  OpenDocument = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  OpenPres = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  OpenSheet = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
}

export enum AudioMediaTypesEnum {
  Aac = "audio/aac",
  Mp4 = "audio/mp4",
  Mpeg = "audio/mpeg",
  Amr = "audio/amr",
  Ogg = "audio/ogg",
}

export enum WebhookTypesEnum {
  Audio = "audio",
  Button = "button",
  Document = "document",
  Text = "text",
  Image = "image",
  Interactive = "interactive",
  Order = "order",
  Sticker = "sticker",
  System = "system",
  Unknown = "unknown",
  Video = "video",
}

export enum SystemChangeTypesEnum {
  CustomerChangedNumber = "customer_changed_number",
  CustomerIdentityChanged = "customer_identity_changed",
}

export enum ReferralSourceTypesEnum {
  Ad = "ad",
  Post = "post",
}

export enum RequestCodeMethodsEnum {
  Sms = "SMS",
  Voice = "VOICE",
}

export enum LanguagesEnum {
  Afrikaans = "af",
  Albanian = "sq",
  Arabic = "ar",
  Azerbaijani = "az",
  Bengali = "bn",
  Bulgarian = "bg",
  Catalan = "ca",
  Chinese_CHN = "zh_CN",
  Chinese_HKG = "zh_HK",
  Chinese_TAI = "zh_TW",
  Croatian = "hr",
  Czech = "cs",
  Danish = "da",
  Dutch = "nl",
  English = "en",
  English_UK = "en_GB",
  English_US = "en_US",
  Estonian = "et",
  Filipino = "fil",
  Finnish = "fi",
  French = "fr",
  Georgian = "ka",
  German = "de",
  Greek = "el",
  Gujarati = "gu",
  Hausa = "ha",
  Hebrew = "he",
  Hindi = "hi",
  Hungarian = "hu",
  Indonesian = "id",
  Irish = "ga",
  Italian = "it",
  Japanese = "ja",
  Kannada = "kn",
  Kazakh = "kk",
  Kinyarwanda = "rw_RW",
  Korean = "ko",
  Kyrgyz_Kyrgyzstan = "ky_KG",
  Lao = "lo",
  Latvian = "lv",
  Lithuanian = "lt",
  Macedonian = "mk",
  Malay = "ms",
  Malayalam = "ml",
  Marathi = "mr",
  Norwegian = "nb",
  Persian = "fa",
  Polish = "pl",
  Portuguese_BR = "pt_BR",
  Portuguese_POR = "pt_PT",
  Punjabi = "pa",
  Romanian = "ro",
  Russian = "ru",
  Serbian = "sr",
  Slovak = "sk",
  Slovenian = "sl",
  Spanish = "es",
  Spanish_ARG = "es_AR",
  Spanish_SPA = "es_ES",
  Spanish_MEX = "es_MX",
  Swahili = "sw",
  Swedish = "sv",
  Tamil = "ta",
  Telugu = "te",
  Thai = "th",
  Turkish = "tr",
  Ukrainian = "uk",
  Urdu = "ur",
  Uzbek = "uz",
  Vietnamese = "vi",
  Zulu = "zu",
}

export enum CurrencyCodesEnum {
  AFN = "AFN",
  EUR = "EUR",
  ALL = "ALL",
  DZD = "DZD",
  USD = "USD",
  AOA = "AOA",
  XCD = "XCD",
  ARS = "ARS",
  AMD = "AMD",
  AWG = "AWG",
  AUD = "AUD",
  AZN = "AZN",
  BSD = "BSD",
  BHD = "BHD",
  BDT = "BDT",
  BBD = "BBD",
  BYN = "BYN",
  BZD = "BZD",
  XOF = "XOF",
  BMD = "BMD",
  INR = "INR",
  BTN = "BTN",
  BOB = "BOB",
  BOV = "BOV",
  BAM = "BAM",
  BWP = "BWP",
  NOK = "NOK",
  BRL = "BRL",
  BND = "BND",
  BGN = "BGN",
  BIF = "BIF",
  CVE = "CVE",
  KHR = "KHR",
  XAF = "XAF",
  CAD = "CAD",
  KYD = "KYD",
  CLP = "CLP",
  CLF = "CLF",
  CNY = "CNY",
  COP = "COP",
  COU = "COU",
  KMF = "KMF",
  CDF = "CDF",
  NZD = "NZD",
  CRC = "CRC",
  HRK = "HRK",
  CUP = "CUP",
  CUC = "CUC",
  ANG = "ANG",
  CZK = "CZK",
  DKK = "DKK",
  DJF = "DJF",
  DOP = "DOP",
  EGP = "EGP",
  SVC = "SVC",
  ERN = "ERN",
  SZL = "SZL",
  ETB = "ETB",
  FKP = "FKP",
  FJD = "FJD",
  XPF = "XPF",
  GMD = "GMD",
  GEL = "GEL",
  GHS = "GHS",
  GIP = "GIP",
  GTQ = "GTQ",
  GBP = "GBP",
  GNF = "GNF",
  GYD = "GYD",
  HTG = "HTG",
  HNL = "HNL",
  HKD = "HKD",
  HUF = "HUF",
  ISK = "ISK",
  IDR = "IDR",
  XDR = "XDR",
  IRR = "IRR",
  IQD = "IQD",
  ILS = "ILS",
  JMD = "JMD",
  JPY = "JPY",
  JOD = "JOD",
  KZT = "KZT",
  KES = "KES",
  KPW = "KPW",
  KRW = "KRW",
  KWD = "KWD",
  KGS = "KGS",
  LAK = "LAK",
  LBP = "LBP",
  LSL = "LSL",
  ZAR = "ZAR",
  LRD = "LRD",
  LYD = "LYD",
  CHF = "CHF",
  MOP = "MOP",
  MKD = "MKD",
  MGA = "MGA",
  MWK = "MWK",
  MYR = "MYR",
  MVR = "MVR",
  MRU = "MRU",
  MUR = "MUR",
  XUA = "XUA",
  MXN = "MXN",
  MXV = "MXV",
  MDL = "MDL",
  MNT = "MNT",
  MAD = "MAD",
  MZN = "MZN",
  MMK = "MMK",
  NAD = "NAD",
  NPR = "NPR",
  NIO = "NIO",
  NGN = "NGN",
  OMR = "OMR",
  PKR = "PKR",
  PAB = "PAB",
  PGK = "PGK",
  PYG = "PYG",
  PEN = "PEN",
  PHP = "PHP",
  PLN = "PLN",
  QAR = "QAR",
  RON = "RON",
  RUB = "RUB",
  RWF = "RWF",
  SHP = "SHP",
  WST = "WST",
  STN = "STN",
  SAR = "SAR",
  RSD = "RSD",
  SCR = "SCR",
  SLL = "SLL",
  SGD = "SGD",
  XSU = "XSU",
  SBD = "SBD",
  SOS = "SOS",
  SSP = "SSP",
  LKR = "LKR",
  SDG = "SDG",
  SRD = "SRD",
  SEK = "SEK",
  CHE = "CHE",
  CHW = "CHW",
  SYP = "SYP",
  TWD = "TWD",
  TJS = "TJS",
  TZS = "TZS",
  THB = "THB",
  TOP = "TOP",
  TTD = "TTD",
  TND = "TND",
  TRY = "TRY",
  TMT = "TMT",
  UGX = "UGX",
  UAH = "UAH",
  AED = "AED",
  USN = "USN",
  UYU = "UYU",
  UYI = "UYI",
  UYW = "UYW",
  UZS = "UZS",
  VUV = "VUV",
  VES = "VES",
  VND = "VND",
  YER = "YER",
  ZMW = "ZMW",
  ZWL = "ZWL",
  XBA = "XBA",
  XBB = "XBB",
  XBC = "XBC",
  XBD = "XBD",
  XTS = "XTS",
  XXX = "XXX",
  XAU = "XAU",
  XPD = "XPD",
  XPT = "XPT",
  XAG = "XAG",
  AFA = "AFA",
  FIM = "FIM",
  ALK = "ALK",
  ADP = "ADP",
  ESP = "ESP",
  FRF = "FRF",
  AOK = "AOK",
  AON = "AON",
  AOR = "AOR",
  ARA = "ARA",
  ARP = "ARP",
  ARY = "ARY",
  RUR = "RUR",
  ATS = "ATS",
  AYM = "AYM",
  AZM = "AZM",
  BYB = "BYB",
  BYR = "BYR",
  BEC = "BEC",
  BEF = "BEF",
  BEL = "BEL",
  BOP = "BOP",
  BAD = "BAD",
  BRB = "BRB",
  BRC = "BRC",
  BRE = "BRE",
  BRN = "BRN",
  BRR = "BRR",
  BGJ = "BGJ",
  BGK = "BGK",
  BGL = "BGL",
  BUK = "BUK",
  HRD = "HRD",
  CYP = "CYP",
  CSJ = "CSJ",
  CSK = "CSK",
  ECS = "ECS",
  ECV = "ECV",
  GQE = "GQE",
  EEK = "EEK",
  XEU = "XEU",
  GEK = "GEK",
  DDM = "DDM",
  DEM = "DEM",
  GHC = "GHC",
  GHP = "GHP",
  GRD = "GRD",
  GNE = "GNE",
  GNS = "GNS",
  GWE = "GWE",
  GWP = "GWP",
  ITL = "ITL",
  ISJ = "ISJ",
  IEP = "IEP",
  ILP = "ILP",
  ILR = "ILR",
  LAJ = "LAJ",
  LVL = "LVL",
  LVR = "LVR",
  LSM = "LSM",
  ZAL = "ZAL",
  LTL = "LTL",
  LTT = "LTT",
  LUC = "LUC",
  LUF = "LUF",
  LUL = "LUL",
  MGF = "MGF",
  MVQ = "MVQ",
  MLF = "MLF",
  MTL = "MTL",
  MTP = "MTP",
  MRO = "MRO",
  MXP = "MXP",
  MZE = "MZE",
  MZM = "MZM",
  NLG = "NLG",
  NIC = "NIC",
  PEH = "PEH",
  PEI = "PEI",
  PES = "PES",
  PLZ = "PLZ",
  PTE = "PTE",
  ROK = "ROK",
  ROL = "ROL",
  STD = "STD",
  CSD = "CSD",
  SKK = "SKK",
  SIT = "SIT",
  RHD = "RHD",
  ESA = "ESA",
  ESB = "ESB",
  SDD = "SDD",
  SDP = "SDP",
  SRG = "SRG",
  CHC = "CHC",
  TJR = "TJR",
  TPE = "TPE",
  TRL = "TRL",
  TMM = "TMM",
  UGS = "UGS",
  UGW = "UGW",
  UAK = "UAK",
  SUR = "SUR",
  USS = "USS",
  UYN = "UYN",
  UYP = "UYP",
  VEB = "VEB",
  VEF = "VEF",
  VNC = "VNC",
  YDD = "YDD",
  YUD = "YUD",
  YUM = "YUM",
  YUN = "YUN",
  ZRN = "ZRN",
  ZRZ = "ZRZ",
  ZMK = "ZMK",
  ZWC = "ZWC",
  ZWD = "ZWD",
  ZWN = "ZWN",
  ZWR = "ZWR",
  XFO = "XFO",
  XRE = "XRE",
  XFU = "XFU",
}

export enum WhatsappTemplateNameEnum {
  UserMealSummary = "user_meal_summary",
  ReminderToPostMealsOne = "reminder_to_post_meals_1",
  ReminderToPostMealsTwo = "reminder_to_post_meals_2",
  ReminderToPostMealsThree = "reminder_to_post_meals_3",
  MealReport = "user_meal_report",
  WelcomeMessage = "welcome_message",
}

export enum CountryCodeToDefaultTimezoneEnum {
  AF = "Asia/Kabul",
  AL = "Europe/Tirane",
  DZ = "Africa/Algiers",
  AO = "Africa/Luanda",
  AR = "America/Argentina/Buenos_Aires",
  AM = "Asia/Yerevan",
  AU = "Australia/Sydney",
  AT = "Europe/Vienna",
  AZ = "Asia/Baku",
  BH = "Asia/Bahrain",
  BD = "Asia/Dhaka",
  BY = "Europe/Minsk",
  BE = "Europe/Brussels",
  BJ = "Africa/Porto-Novo",
  BT = "Asia/Thimphu",
  BO = "America/La_Paz",
  BA = "Europe/Sarajevo",
  BW = "Africa/Gaborone",
  BR = "America/Sao_Paulo",
  BG = "Europe/Sofia",
  BF = "Africa/Ouagadougou",
  BI = "Africa/Bujumbura",
  KH = "Asia/Phnom_Penh",
  CM = "Africa/Douala",
  CA = "America/Toronto",
  CL = "America/Santiago",
  CN = "Asia/Shanghai",
  CO = "America/Bogota",
  CR = "America/Costa_Rica",
  HR = "Europe/Zagreb",
  CU = "America/Havana",
  CY = "Asia/Nicosia",
  CZ = "Europe/Prague",
  DK = "Europe/Copenhagen",
  DO = "America/Santo_Domingo",
  EC = "America/Guayaquil",
  EG = "Africa/Cairo",
  SV = "America/El_Salvador",
  EE = "Europe/Tallinn",
  ET = "Africa/Addis_Ababa",
  FI = "Europe/Helsinki",
  FR = "Europe/Paris",
  GA = "Africa/Libreville",
  GM = "Africa/Banjul",
  GE = "Asia/Tbilisi",
  DE = "Europe/Berlin",
  GH = "Africa/Accra",
  GR = "Europe/Athens",
  GT = "America/Guatemala",
  HN = "America/Tegucigalpa",
  HU = "Europe/Budapest",
  IS = "Atlantic/Reykjavik",
  IN = "Asia/Kolkata",
  ID = "Asia/Jakarta",
  IR = "Asia/Tehran",
  IQ = "Asia/Baghdad",
  IE = "Europe/Dublin",
  IL = "Asia/Jerusalem",
  IT = "Europe/Rome",
  JM = "America/Jamaica",
  JP = "Asia/Tokyo",
  JO = "Asia/Amman",
  KZ = "Asia/Almaty",
  KE = "Africa/Nairobi",
  KR = "Asia/Seoul",
  KW = "Asia/Kuwait",
  LA = "Asia/Vientiane",
  LV = "Europe/Riga",
  LB = "Asia/Beirut",
  LY = "Africa/Tripoli",
  LT = "Europe/Vilnius",
  LU = "Europe/Luxembourg",
  MG = "Indian/Antananarivo",
  MY = "Asia/Kuala_Lumpur",
  MV = "Indian/Maldives",
  ML = "Africa/Bamako",
  MT = "Europe/Malta",
  MX = "America/Mexico_City",
  MN = "Asia/Ulaanbaatar",
  MA = "Africa/Casablanca",
  MZ = "Africa/Maputo",
  MM = "Asia/Yangon",
  NA = "Africa/Windhoek",
  NP = "Asia/Kathmandu",
  NL = "Europe/Amsterdam",
  NZ = "Pacific/Auckland",
  NI = "America/Managua",
  NG = "Africa/Lagos",
  NO = "Europe/Oslo",
  OM = "Asia/Muscat",
  PK = "Asia/Karachi",
  PA = "America/Panama",
  PY = "America/Asuncion",
  PE = "America/Lima",
  PH = "Asia/Manila",
  PL = "Europe/Warsaw",
  PT = "Europe/Lisbon",
  QA = "Asia/Qatar",
  RO = "Europe/Bucharest",
  RU = "Europe/Moscow",
  SA = "Asia/Riyadh",
  SN = "Africa/Dakar",
  RS = "Europe/Belgrade",
  SG = "Asia/Singapore",
  SK = "Europe/Bratislava",
  SI = "Europe/Ljubljana",
  ZA = "Africa/Johannesburg",
  ES = "Europe/Madrid",
  LK = "Asia/Colombo",
  SE = "Europe/Stockholm",
  CH = "Europe/Zurich",
  TH = "Asia/Bangkok",
  TN = "Africa/Tunis",
  TR = "Europe/Istanbul",
  UA = "Europe/Kyiv",
  AE = "Asia/Dubai",
  GB = "Europe/London",
  US = "America/New_York",
  UY = "America/Montevideo",
  UZ = "Asia/Tashkent",
  VE = "America/Caracas",
  VN = "Asia/Ho_Chi_Minh",
  ZM = "Africa/Lusaka",
  // ZW = "Africa/Harare",
}

export enum CountryCodeToNameEnum {
  AF = "Afghanistan",
  AL = "Albania",
  DZ = "Algeria",
  AO = "Angola",
  AR = "Argentina",
  AM = "Armenia",
  AU = "Australia",
  AT = "Austria",
  AZ = "Azerbaijan",
  BH = "Bahrain",
  BD = "Bangladesh",
  BY = "Belarus",
  BE = "Belgium",
  BJ = "Benin",
  BT = "Bhutan",
  BO = "Bolivia",
  BA = "Bosnia and Herzegovina",
  BW = "Botswana",
  BR = "Brazil",
  BG = "Bulgaria",
  BF = "Burkina Faso",
  BI = "Burundi",
  KH = "Cambodia",
  CM = "Cameroon",
  CA = "Canada",
  CV = "Cape Verde",
  CF = "Central African Republic",
  TD = "Chad",
  CL = "Chile",
  CN = "China",
  CO = "Colombia",
  KM = "Comoros",
  CG = "Congo (Brazzaville)",
  CD = "Congo (Kinshasa)",
  CR = "Costa Rica",
  CI = "Côte d’Ivoire",
  HR = "Croatia",
  CU = "Cuba",
  CY = "Cyprus",
  CZ = "Czech Republic",
  DK = "Denmark",
  DJ = "Djibouti",
  DM = "Dominica",
  DO = "Dominican Republic",
  EC = "Ecuador",
  EG = "Egypt",
  SV = "El Salvador",
  GQ = "Equatorial Guinea",
  ER = "Eritrea",
  EE = "Estonia",
  SZ = "Eswatini",
  ET = "Ethiopia",
  FJ = "Fiji",
  FI = "Finland",
  FR = "France",
  GA = "Gabon",
  GM = "Gambia",
  GE = "Georgia",
  DE = "Germany",
  GH = "Ghana",
  GR = "Greece",
  GD = "Grenada",
  GT = "Guatemala",
  GN = "Guinea",
  GW = "Guinea-Bissau",
  GY = "Guyana",
  HT = "Haiti",
  HN = "Honduras",
  HU = "Hungary",
  IS = "Iceland",
  IN = "India",
  ID = "Indonesia",
  IR = "Iran",
  IQ = "Iraq",
  IE = "Ireland",
  IL = "Israel",
  IT = "Italy",
  JM = "Jamaica",
  JP = "Japan",
  JO = "Jordan",
  KZ = "Kazakhstan",
  KE = "Kenya",
  KI = "Kiribati",
  KP = "Korea (North)",
  KR = "Korea (South)",
  KW = "Kuwait",
  KG = "Kyrgyzstan",
  LA = "Laos",
  LV = "Latvia",
  LB = "Lebanon",
  LS = "Lesotho",
  LR = "Liberia",
  LY = "Libya",
  LI = "Liechtenstein",
  LT = "Lithuania",
  LU = "Luxembourg",
  MG = "Madagascar",
  MW = "Malawi",
  MY = "Malaysia",
  MV = "Maldives",
  ML = "Mali",
  MT = "Malta",
  MH = "Marshall Islands",
  MR = "Mauritania",
  MU = "Mauritius",
  MX = "Mexico",
  FM = "Micronesia",
  MD = "Moldova",
  MC = "Monaco",
  MN = "Mongolia",
  ME = "Montenegro",
  MA = "Morocco",
  MZ = "Mozambique",
  MM = "Myanmar (Burma)",
  NA = "Namibia",
  NR = "Nauru",
  NP = "Nepal",
  NL = "Netherlands",
  NZ = "New Zealand",
  NI = "Nicaragua",
  NE = "Niger",
  NG = "Nigeria",
  NO = "Norway",
  OM = "Oman",
  PK = "Pakistan",
  PW = "Palau",
  PS = "Palestine",
  PA = "Panama",
  PG = "Papua New Guinea",
  PY = "Paraguay",
  PE = "Peru",
  PH = "Philippines",
  PL = "Poland",
  PT = "Portugal",
  QA = "Qatar",
  RO = "Romania",
  RU = "Russia",
  RW = "Rwanda",
  KN = "Saint Kitts and Nevis",
  LC = "Saint Lucia",
  VC = "Saint Vincent and the Grenadines",
  WS = "Samoa",
  SM = "San Marino",
  ST = "São Tomé and Príncipe",
  SA = "Saudi Arabia",
  SN = "Senegal",
  RS = "Serbia",
  SC = "Seychelles",
  SL = "Sierra Leone",
  SG = "Singapore",
  SK = "Slovakia",
  SI = "Slovenia",
  SB = "Solomon Islands",
  SO = "Somalia",
  ZA = "South Africa",
  SS = "South Sudan",
  ES = "Spain",
  LK = "Sri Lanka",
  SD = "Sudan",
  SR = "Suriname",
  SE = "Sweden",
  CH = "Switzerland",
  SY = "Syria",
  TW = "Taiwan",
  TJ = "Tajikistan",
  TZ = "Tanzania",
  TH = "Thailand",
  TL = "Timor-Leste",
  TG = "Togo",
  TO = "Tonga",
  TT = "Trinidad and Tobago",
  TN = "Tunisia",
  TR = "Turkey",
  TM = "Turkmenistan",
  TV = "Tuvalu",
  UG = "Uganda",
  UA = "Ukraine",
  AE = "United Arab Emirates",
  GB = "United Kingdom",
  US = "United States",
  UY = "Uruguay",
  UZ = "Uzbekistan",
  VU = "Vanuatu",
  VE = "Venezuela",
  VN = "Vietnam",
  YE = "Yemen",
  ZM = "Zambia",
  ZW = "Zimbabwe",
}

export enum GenderEnum {
  Male = "male",
  Female = "female",
  Other = "other",
}

export enum ExerciseRoutineEnum {
  None = "None",
  Light = "Light",
  Moderate = "Moderate",
  Intense = "Intense",
}

export enum SleepPatternsEnum {
  Poor = "Poor (<5 hours)",
  Average = "Average (6-7 hours)",
  Good = "Good (8+ hours)",
}

export enum StressLevelsEnum {
  Low = "Low",
  Moderate = "Moderate",
  High = "High",
}

export enum HeightUnitEnum {
  CM = "cm",
}

export enum WeightUnitEnum {
  KG = "kg",
}

export enum PaymentGatewaysEnum {
  Razorpay = "razorpay",
}

export enum OrderStatusEnum {
  Created = "created",
  Attempted = "attempted",
  Paid = "paid",
}
